name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: make pan-gwes
      working-directory: ./sw/pangwes
      run: make

    - name: Install apt-get deps
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential wget zlib1g-dev libncurses5-dev libbz2-dev liblzma-dev libboost-all-dev libtbb-dev

    - name: Build and Install cuttlefish
      run: |
        wget https://github.com/COMBINE-lab/cuttlefish/archive/refs/tags/v2.2.0.tar.gz
        tar -xvzf v2.2.0.tar.gz
        cd cuttlefish-2.2.0
        mkdir build && cd build/
        cmake -DCMAKE_INSTALL_PREFIX=../ ..
        make -j 8 install
        cd ..
        # ls -lRh
        sudo cp bin/cuttlefish /usr/local/bin/
        cuttlefish version

    - name: Build and Install SpydrPick
      run: |
        wget https://github.com/santeripuranen/SpydrPick/archive/refs/tags/v1.3.0.tar.gz
        tar -xvzf v1.3.0.tar.gz
        cd SpydrPick-1.3.0
        mkdir build && cd build/
        cmake ..
        make SpydrPick
        cd ..
        ls -lRh

    - name: Download test data
      run: |
        wget https://raw.githubusercontent.com/Sudaraka88/PAN-GWES_testdata/main/efcls_assemblies_subset.tar.gz
        tar -xvzf efcls_assemblies_subset.tar.gz
        ls -lRh

        
