name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install apt-get deps
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential wget zlib1g-dev libncurses5-dev libbz2-dev liblzma-dev # libboost-all-dev libtbb-dev

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pangwes
    - name: Conda info
      shell: bash -el {0}
      run: conda info
  
    - name: Install SpydrPick from Bioconda
      run: |
        conda install -c bioconda -c conda-forge spydrpick
        conda info
        SpydrPick -h

    # - name: Download Spydrpick+apegrunt and set up paths 
    #   run: |
    #     wget https://github.com/santeripuranen/apegrunt/archive/refs/tags/v0.5.0.tar.gz
    #     tar -xvzf v0.5.0.tar.gz
    #     wget https://github.com/santeripuranen/SpydrPick/archive/refs/tags/v1.3.0.tar.gz
    #     tar -xvzf v1.3.0.tar.gz
    #     mv apegrunt-0.5.0/* SpydrPick-1.3.0/externals/apegrunt
    #     ls -lRh SpydrPick-1.3.0
    
    # - name: Build and Install SpydrPick
    #   run: |
    #     cd SpydrPick-1.3.0
    #     awk 'NR==1{print "CMAKE_POLICY ( SET CMP0004 OLD )"}1' src/CMakeLists.txt > src/CMakeLists.txt
    #     head src/CMakeLists.txt
    #     mkdir build && cd build/
    #     cmake ..
    #     make # SpydrPick
    #     cd ..
    #     ls -lRh

    - name: Build and Install cuttlefish
      run: |
        wget https://github.com/COMBINE-lab/cuttlefish/archive/refs/tags/v2.2.0.tar.gz
        tar -xvzf v2.2.0.tar.gz
        cd cuttlefish-2.2.0
        mkdir build && cd build/
        cmake -DCMAKE_INSTALL_PREFIX=../ ..
        make -j 4 install
        cd ..
        # ls -lRh
        sudo cp bin/cuttlefish /usr/local/bin/
        cuttlefish version

    - name: Build pan-gwes
      working-directory: ./sw/pangwes
      run: make

    - name: Download test data
      run: |
        wget https://raw.githubusercontent.com/Sudaraka88/PAN-GWES_testdata/main/efcls_assemblies_subset.tar.gz
        tar -xvzf efcls_assemblies_subset.tar.gz
        # ls -lRh
