name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: make
      working-directory: ./sw/pangwes
      run: make

    - name: Build and Install cuttlefish
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential wget zlib1g-dev libncurses5-dev libbz2-dev liblzma-dev
        wget https://github.com/COMBINE-lab/cuttlefish/archive/refs/tags/v2.2.0.tar.gz
        tar -xvzf v2.2.0.tar.gz
        cd cuttlefish-2.2.0
        mkdir build && cd build/
        cmake -DCMAKE_INSTALL_PREFIX=../ ..
        make -j 8 install
        cd ..
        ls

        
